### ISSUE TITLE
ModuleNotFoundError: No module named 'pymdownx'

### ISSUE THREAD

**Issue by mpagot** [igsekor/pyspelling-any#3]
I'd use this action with a set of Markdown files. My [.spellcheck.yml](https://github.com/mpagot/docuparty/blob/fix-spellcheck/.spellcheck.yml)

```
matrix:
- name: markdown
  pipeline:
    - pyspelling.filters.markdown:
        markdown_extensions:
        - pymdownx.superfences:
        - pymdownx.highlight:
  sources:
  - '**/*.md'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - en-custom.txt
    output: build/dictionary/python.dic
  default_encoding: utf-8
```

https://github.com/mpagot/docuparty/runs/7693190419?check_suite_focus=true

Full log
```
/usr/bin/docker run --name igsekorpyspellingany_e5b864 --label 4cd98f --workdir /github/workspace --rm -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/docuparty/docuparty":"/github/workspace" igsekor/pyspelling-any
Starting...
Setup languages and spelling tool...
Reading package lists...
Building dependency tree...
Reading state information...
aspell-en is already the newest version (2018.04.16-0-1).
aspell-en set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and [3](https://github.com/mpagot/docuparty/runs/7693190419?check_suite_focus=true#step:5:4) not upgraded.
Using PySpelling according to configuration from .spellcheck.yml
Traceback (most recent call last):
  File "/usr/local/bin/pyspelling", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pyspelling/__main__.py", line 26, in main
    return run(
  File "/usr/local/lib/python3.9/site-packages/pyspelling/__main__.py", line 51, in run
    for results in spellcheck(
  File "/usr/local/lib/python3.9/site-packages/pyspelling/__init__.py", line 673, in spellcheck
    for result in spellchecker.run_task(task, source_patterns=sources):
  File "/usr/local/lib/python3.9/site-packages/pyspelling/__init__.py", line 311, in run_task
    self._build_pipeline(task)
  File "/usr/local/lib/python3.9/site-packages/pyspelling/__init__.py", line 265, in _build_pipeline
    self.pipeline_steps.append(module(options, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/pyspelling/filters/markdown.py", line 13, in __init__
    super().__init__(options, default_encoding)
  File "/usr/local/lib/python3.9/site-packages/pyspelling/filters/__init__.py", line 86, in __init__
    super().__init__(options)
  File "/usr/local/lib/python3.9/site-packages/pyspelling/plugin.py", line 23, in __init__
    self.setup()
  File "/usr/local/lib/python3.9/site-packages/pyspelling/filters/markdown.py", line 35, in setup
    self.markdown = markdown.Markdown(extensions=extensions, extension_configs=extension_configs)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 162, in build_extension
    module = importlib.import_module(ext_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 98[4](https://github.com/mpagot/docuparty/runs/7693190419?check_suite_focus=true#step:5:5), in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pymdownx'
Files in repository contain spelling errors
```

**Comment by rustydb** [comment]
Also hitting this.

**Comment by jonasbn** [comment]
Hi @mpagot and @rustydb 

The [Dockerfile](https://github.com/igsekor/pyspelling-any/blob/main/Dockerfile) does not seem to include these extra modules, which can be configured for **PySpelling** briefly touched on [in the documentation](https://facelessuser.github.io/pyspelling/filters/markdown/)

**Comment by mpagot** [comment]
Ok thanks. Fixed on my side with something like https://github.com/mpagot/docuparty/commit/4bbfa5e34b3a47012cd34e9e4d9989eae52bea60

I changed the github action and correctly populated the .spellcheck.yml

A good article about it in https://www.javierbrea.com/blog/spellcheck-github-action/
